version: "3"
services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3100:3100"
    volumes:
      - ./src:/usr/app/src
      - ./data:/usr/app/data
    environment:
      - CHOKIDAR_USEPOLLING=true
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/usr/app/src
      - ./client/public:/usr/app/public
    environment:
      - REACT_APP_API_URL=http://${DOCKER_MACHINE_IP}:3100
      - CHOKIDAR_USEPOLLING=true
      - CI=true
